# Generated by Django 3.2.7 on 2022-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220623_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailphoto',
            field=models.CharField(max_length=500, null=True, verbose_name='상품사진'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=500, null=True, verbose_name='상품사진'),
        ),
    ]
