# Generated by Django 3.2.7 on 2022-06-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_content_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='product.product')),
            ],
            options={
                'verbose_name': '해시태그',
                'verbose_name_plural': '해시태그',
            },
        ),
    ]
