# Generated by Django 3.2.7 on 2022-06-28 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_hashtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='평점')),
                ('context', models.TextField(verbose_name='후기내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '후기',
                'verbose_name_plural': '후기',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=256, verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='review.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '답글',
                'verbose_name_plural': '답글',
            },
        ),
    ]
